### ISSUE TITLE
jest generates error: Cannot find module 'use-pouchdb'

### ISSUE THREAD

**Issue by jnnwnk** [Terreii/use-pouchdb#39]
## Description

We started using `use-pouchdb` in one of our projects.
It actually works very well. The connection to the database was quick and easy.
But for some reason the execution of the tests is not possible anymore.
As soon as a component is to be rendered that has an import from use-pouchdb, the following error is generated:
```
Cannot find module 'use-pouchdb' from '<path-to-component>.js'.
```
No component from `use-pouchdb` is used, only the import is available.
To isolate the error, I created a new project via `npx create-react-app`. Here I can recreate the error in the same way, so that I would exclude side effects from other dependencies in my project.

## Steps to Reproduce

- `npx create-react-app my-app`
- `cd ./my-app`
- `npm i use-pouchdb`
- Modify `App.test.js`: Add to imports: `import { Provider } from "use-pouchdb";`
- `npm run test`

## Expected Behavior

Test should succeed.

## Your Environment

- package.json
    ```json
    {
      "name": "my-app",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@testing-library/jest-dom": "^4.2.4",
        "@testing-library/react": "^9.5.0",
        "@testing-library/user-event": "^7.2.1",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-scripts": "3.4.3",
        "use-pouchdb": "^1.2.0"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": "react-app"
      },
      "browserslist": {
        "production": [
          ">0.2%",
          "not dead",
          "not op_mini all"
        ],
        "development": [
          "last 1 chrome version",
          "last 1 firefox version",
          "last 1 safari version"
        ]
      }
    }
    ```

- App.test.js
	```js
	import React from 'react';
	import { render } from '@testing-library/react';
	import App from './App';
	import { Provider } from "use-pouchdb";

	test('renders learn react link', () => {
	  const { getByText } = render(
	  <App />);
	  const linkElement = getByText(/learn react/i);
	  expect(linkElement).toBeInTheDocument();
	});
	```
- Operating system and version: Windows 10 Pro, 64 Bit

**Comment by Terreii** [comment]
😬 Oh. That's what you get if your (my) test-app has no tests.

I could reproduce the bug and have a fix on the way.

Thanks for using my package!
