### ISSUE TITLE
`useAllDocs` not subscribing to updates

### ISSUE THREAD

**Issue by samifreesoul** [Terreii/use-pouchdb#77]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description
I'm using your [todo example](https://terreii.github.io/use-pouchdb/docs/basics/list-all) and although the todo-list is shown on the page and new todos are added using the form, the new todo won't be shown until I reload the page.    

## Steps to Reproduce
1. Install dependencies
```
npm i pouchdb-browser use-pouchdb pouchdb-node express-pouchdb
```
2. Create `src/AddTodo.js`:
```import React from "react";
import { usePouch } from "use-pouchdb";

export default function AddTodo() {
  const db = usePouch();

  const [input, setInput] = React.useState("");

  const handleAddTodo = async (event) => {
    event.preventDefault();

    const doc = {
      _id: new Date().toJSON(),
      type: "todo",
      text: input,
      done: false
    };

    await db.put(doc);

    setInput("");
  };

  return (
    <form onSubmit={handleAddTodo}>
      <input
        type="text"
        value={input}
        minLength={1}
        onChange={(event) => {
          setInput(event.target.value);
        }}
      />

      <button>Add Todo</button>
    </form>
  );
}
```
3. Create `src/TodoList.js`
```
import React from "react";
import { useAllDocs } from "use-pouchdb";
const Todo = ({ todo }) => {
  return (
    <li className="todo-item">
      <span className="todo-item__text">{todo.text}</span>
    </li>
  );
};

export default function TodoList() {
  const { rows: todos, loading } = useAllDocs({
    include_docs: true
  });

  return (
    <ul className="todo-list">
      {(todos && todos.length) || loading
        ? todos.map((todo) => <Todo key={todo.key} todo={todo.doc} />)
        : "No todos, yay!"}
    </ul>
  );
}
```
4. Modify App.js so it uses `TodoList` and `AddTodo` and also the `Provider`:
```
import "./styles.css";
import React, { useEffect } from "react";
import PouchDB from "pouchdb-browser";
import { Provider } from "use-pouchdb";
import AddTodo from "./AddTodo";
import TodoList from "./TodoList";

export default function App() {
  const [db, setDB] = React.useState(() => new PouchDB("local"));

  useEffect(() => {
    const listener = (dbName) => {
      if (dbName === "local") {
        setDB(new PouchDB("local"));
      }
    };

    PouchDB.on("destroyed", listener);

    return () => {
      PouchDB.removeListener("destroyed", listener);
    };
  }, []);

  return (
    <Provider pouchdb={db}>
      <div className="App">
        <AddTodo />
        <TodoList />
      </div>
    </Provider>
  );
}
```
5. Create `src/setupProxy.js`:
```
// The node version of PouchDB (without browser stuff)
const PouchDB = require("pouchdb-node");
const expressPouchDB = require("express-pouchdb");

const PrefixedPouch = PouchDB.defaults({
  prefix: "db/" // All PouchDB data will be stored in the directory ./db/*
});

module.exports = function (app) {
  // app is the Create-React-App dev server.
  // Our databases will be available at http://localhost:3000/db/*
  app.use("/db", expressPouchDB(PrefixedPouch));
};

```
6. Run the server
```
npm start
```
7. In the browser, type something in the form
8. Click "Add Todo" or hit enter.
9. Notice that the todo isn't shown in the page and therefore, useAllDocs isn't subscribed to updates.
10. Check IndexedDB in dev tools to see that the todo has been successfully added.
11. Reload to see it get's added to the page after reload.

[Here](https://codesandbox.io/s/usepouchdb-tutorial-1kl9c4?file=/src/App.js)'s the codesandbox just in case.

## Expected Behavior
Todo Item is expected to appear in the browser without reloading the page(useAllDocs being subscribed to updates)

## Your Environment
use-pouchdb version 1.3.3 
pouchdb-browser version 7.3.0
express-pouchdb 4.2.0
pouchdb-node 7.3.0

- CouchDB version used: no CouchDB server, everything offline.
- PouchDB version used: no PouchDB server
- React version used: 18.0.0
- Browser name and version: Chrome 101.0.4951.64 (Official Build) (arm64)
- Operating system and version: macOS Big Sur 11.2.2

## Additional Context

Thanks in advance for any help you're able to provide.

**Comment by chromakode** [comment]
I believe this is being caused by React 18's [Strict Mode mount and unmount behavior](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state). I noticed this in a project using React 18 as well.

**Comment by Terreii** [comment]
Sorry for the late response.

@chromakode is right, it is the strict-mode.
