### ISSUE TITLE
db.type() is deprecated

### ISSUE THREAD

**Issue by jon-vfb** [Terreii/use-pouchdb#84]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description

Basically I started having this warning on my console: 
`db.type() is deprecated and will be removed in a future version of PouchDB`
I think this is related to the current version of usePouch, and I just wanted to give a heads up to see if this can be updated.

## Steps to Reproduce

just using usePouch will show this warning on the console

**Comment by Terreii** [comment]
`db.type()` in not used in this package.
